<?php

use Hyva\AmastyRewards\ViewModel\Catalog\HighlightProduct;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Framework\Escaper;

/** @var ViewModelRegistry $viewModels */
/** @var Escaper $escaper */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

/** @var Highlight $viewModel */
$viewModel = $viewModels->require(HighlightProduct::class);

$uniqueScriptId = uniqid();
?>

<script>
    function initGuestHighlight_<?= $uniqueScriptId ?>() {
        return {
            highlight: <?= /** @noEscape */ json_encode($viewModel->getJsConfig()) ?> || { visible: false }
        }
    }
</script>

<div x-data="initGuestHighlight_<?= $uniqueScriptId ?>()"
     class="amasty-rewards-highlight-catalog">

    <div x-show="highlight.visible" class="amrewards-highlight-container flex">
        <?= $heroicons->currencyDollarHtml("w-5", 25, 25) ?>
        <div class="caption ml-1">
            <strong>
                <?= $escaper->escapeHtml(__('You can earn')) ?>
                <b x-text="highlight.caption_text" :style="`color: ${highlight.caption_color};`"></b>
                <?= $escaper->escapeHtml(__('for registration!')) ?>
            </strong>
        </div>
    </div>

</div>
