<?php
use Hyva\AmastyRewards\ViewModel\Catalog\HighlightCategory;
use Magento\Framework\Escaper;

/** @var ViewModelRegistry $viewModels */
/** @var Escaper $escaper */

/** @var HighlightCategory $viewModel */
$viewModel = $viewModels->require(HighlightCategory::class);

/** @var Magento\Catalog\Model\Product $product */
/** @var Amasty\Rewards\Block\Frontend\Catalog\HighlightCategory $block */
$product = $block->getProduct();

$uniqueScriptId = uniqid();
?>
<script>
    function initHighlightCategory_<?= /** @noEscape */ $uniqueScriptId ?>() {
        return {
            config: <?= /** @noEscape */ $viewModel->getJsConfig($product) ?>,
            visible: false,
            captionText: '',
            captionColor: '',
            updateData(rootEl) {
                const refreshUrl = this.config.refreshUrl;
                const formKey = rootEl.querySelector('input[name="form_key"]').value;
                const attributes = `form_key=${formKey}&product=${this.config.data.product}&uenc=${this.config.data.uenc}`;

                fetch(refreshUrl, {
                    "headers": {
                        'Accept': 'application/json',
                        'Content-Type': 'application/json'
                    },
                    "body": JSON.stringify({
                        "customer_id":  <?= $viewModel->getCustomerId() ?>,
                        "productId": this.config.productId,
                        attributes
                    }),
                    "method": "POST"
                }).then(function (data) {
                    return data.json();
                }).then(response => {
                    console.log(response);

                    // throw new Error(response['error_message']);
                })
            }
        }
    }
</script>


<div x-data="initHighlightCategory_<?= /** @noEscape */ $uniqueScriptId ?>()"
     x-init="updateData($el);"
     class="amasty-rewards-highlight-catalog">

    <?= $block->getBlockHtml('formkey') ?>

    <div class="amasty-rewards-loader" data-bind="visible: loader()" style="display: none;">
        <img src="<?= $escaper->escapeUrl($viewModel->getViewFileUrl('Amasty_Rewards::images/ajax-loader.gif')) ?>" />
    </div>

    <div x-show="visible" class="amrewards-highlight-container">
        <div class="caption">
            <strong>
                <?= $escaper->escapeHtml(__('Earn')) ?>
                <b x-text="captionText" :style="`color: ${captionColor};`"></b>
            </strong>
        </div>
    </div>

</div>
