<?php
// @codingStandardsIgnoreFile
/** @var Amasty\Rewards\Block\Frontend\Balance $block */

$uniqueScriptId = uniqid();
?>

<script>
    function initBalance_<?= $uniqueScriptId ?>() {
        return {
            visible: false,
            captionText: "<?= $block->getBalanceLabel() ?>",
            balance: "<?= $block->getCustomerBalance() ?>",
            getData(data) {
                if (data.rewards) {
                    this.balance = data.rewards.balance
                }
                this.visible = true;
            }
        }
    }
</script>

<a  x-data="initBalance_<?= $uniqueScriptId ?>()"
    @private-content-loaded.window="getData(event.detail.data)"
    href="<?= $block->getUrl('amrewards') ?>"
    class="flex px-4 py-2 lg:px-5 lg:py-2 hover:bg-gray-100"
    x-show="visible">
    <span class="amrewards-label" x-text="captionText"></span>
    <div class="amrewards-amount ml-1 pl-1.5 pr-1.5 bg-yellow-500 font-bold rounded-lg" x-text="balance"></div>
</a>

